### ISSUE TITLE
error python 3.11

### ISSUE THREAD

**Issue by casanos0v0** [casanos0v0/nohcel.qt#2]

**Comment by casanos0v0** [comment]
bcp_batch error

**Comment by lcmd65** [comment]
yah, also using docker to create runtime environment to pass os bug

**Comment by lcmd65** [comment]
can using python 3.10 because python 3.11 is deprecated the os icon for AppKit

**Comment by casanos0v0** [comment]
> yah, also using docker to create runtime environment to pass os bug

ok

**Comment by casanos0v0** [comment]
> can using python 3.10 because python 3.11 is deprecated the os icon for AppKit

ok thanks
